# This workflow builds and tests the project using Maven
name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    # test against several Operating syestem after completion diff jdk(8,11,17) but now this is only for code coverge in CI java 17
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # ubuntu will run 8,11,17 and java 17 will generate code coverage and i added pjacoco + Coveralls
          - os: ubuntu-latest
            java: 17
            additional-maven-args: "-Pjacoco -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"

          # window will run 17
          - os: windows-latest
            java: 17
            additional-maven-args: "-DskipITs"

          # macos will run 17
          - os: macos-latest
            java: 17
            additional-maven-args: "-DskipITs"

    steps:
      # This will Checkout source code .
      - name: Checkout repository
        uses: actions/checkout@v3

      # this is for Set up Java 17
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'

      # Tthis is updated for Cache Maven dependencies .m2
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # This for Build and test with Maven
      - name: Build with Maven
        run: mvn clean verify ${{ matrix.additional-maven-args }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          TESTCONTAINERS_RYUK_DISABLED: true

      # Generate JUnit Report
      - name: Generate JUnit Report
        run: >
          mvn surefire-report:report-only site:site -DgenerateReports=false
        if: ${{ always() }}

      #  Archive JUnit Report
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: surefire-report-${{ matrix.os }}-jdk-${{ matrix.java }}
          path: '**/target/site'