# This workflow builds and tests the project using Maven
name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    # test against several Operating syestem after completion diff jdk(8,11,17) but now this is only for code coverge in CI java 17
    runs-on: ubuntu-latest

    steps:
      # This will Checkout source code .
      - name: Checkout repository
        uses: actions/checkout@v3

      # this is for Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Tthis is updated for Cache Maven dependencies .m2
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk17-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # This for Build and test with Maven
      - name: Build with Maven
        run: mvn clean verify -Pjacoco coveralls:report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      # Generate JUnit Report
      - name: Generate JUnit Report
        run: >
          mvn surefire-report:report-only site:site -DgenerateReports=false
        if: ${{ always() }}

      #  Archive JUnit Report
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: surefire-report-ubuntu-jdk-17
          path: '**/target/site'
