# This workflow builds and tests the project using Maven
name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    # test against several Operating syestem after completion diff jdk(8,11,17):
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # test against several Operating Syestemm:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # test against several Java versions:
        java: [8, 11, 17]
        # excluding unsupported combinations versions will run ubuntu 8,11,17 , window will run 17 and macos will run 17.
        exclude:
          - os: macos-latest
            java: 8
          - os: macos-latest
            java: 11
          - os: windows-latest
            java: 8
          - os: windows-latest
            java: 11

    steps:
      # This will Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # this is for Set up Java 17
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'

      # Tthis is updated for Cache Maven dependencies .m2
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # This for Build and test with Maven
      - name: Build with Maven
        run: mvn clean verify

      # Generate JUnit Report
      - name: Generate JUnit Report
        run: >
		
          mvn surefire-report:report-only 
		  site:site -DgenerateReports=false
        if: ${{ always() }}

      #  Archive JUnit Report
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: surefire-report-jdk-${{ matrix.java }}
          path: '**/target/site'
