# This workflow builds and tests the project using Maven
name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
	# Added strategy matrix for multiple Java versions (8and 11) its was failed.
	# again Added strategy matrix for multiple Java versions (8,11 and 17) also changing in pom 17 to 8 verion because java 8 jobs failed.
    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
      # This will Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # this is for Set up Java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      #Tthis is updated for  Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # This for Build and test with Maven
      - name: Build with Maven
        run: mvn clean verify
