# This workflow builds and tests the project using Maven
name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Added strategy matrix for multiple Java versions (8and 11).
    strategy:
      matrix:
        java: [8, 17]

    steps:
      # This will Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # this is for Set up Java based on matrix
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      #Tthis is updated for  Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # This for Build and test with Maven
      - name: Build with Maven
        run: mvn clean verify
